
export {default as Logo} from './Logo'
export {default as Input} from './Input'
export {default as Title} from './Title'
export {default as Text } from './Text'
export {default as Card} from './Card'
export {default as Button} from './Button'
export {default as Toast } from './Toast'
export {default as Nav} from './Nav'
export {default  as LinkCard } from './LinkCard'
export {default as Migas} from './Migas'
export {default as Tab} from './Tab'
export {default as Empleado} from './Empleado'
export {default as Estado} from './Estado'
export {default as EstadoView} from './EstadoView'
export {default as Prioridad} from './Prioridad'